# Generated by Django 3.2.9 on 2022-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220426_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
