# Generated by Django 3.2.9 on 2022-02-17 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KarekhBanks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('hospitalName', models.CharField(max_length=250, verbose_name='hospitalName')),
                ('hospitalAddress', models.CharField(max_length=255, verbose_name='hospitalAddress')),
                ('bottles', models.IntegerField(max_length=10, verbose_name='bottles')),
                ('hospitalNumber', models.IntegerField(max_length=11, verbose_name='hospitalNumber')),
            ],
        ),
        migrations.CreateModel(
            name='RassafaBanks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('hospitalName', models.CharField(max_length=250, verbose_name='hospitalName')),
                ('hospitalAddress', models.CharField(max_length=255, verbose_name='hospitalAddress')),
                ('bottles', models.IntegerField(max_length=10, verbose_name='bottles')),
                ('hospitalNumber', models.IntegerField(max_length=11, verbose_name='hospitalNumber')),
            ],
        ),
    ]
