# Generated by Django 3.2.9 on 2022-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karekhbanks',
            name='hospitalNumber',
            field=models.IntegerField(verbose_name='hospitalNumber'),
        ),
        migrations.AlterField(
            model_name='rassafabanks',
            name='hospitalNumber',
            field=models.IntegerField(verbose_name='hospitalNumber'),
        ),
    ]
