# Generated by Django 3.2.9 on 2022-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0002_auto_20220217_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karekhbanks',
            name='bottles',
            field=models.IntegerField(verbose_name='bottles'),
        ),
        migrations.AlterField(
            model_name='rassafabanks',
            name='bottles',
            field=models.IntegerField(verbose_name='bottles'),
        ),
    ]
