# Generated by Django 3.2.9 on 2022-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0003_auto_20220217_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karekhbanks',
            name='bottles',
        ),
        migrations.RemoveField(
            model_name='rassafabanks',
            name='bottles',
        ),
        migrations.AddField(
            model_name='karekhbanks',
            name='availableBottles',
            field=models.IntegerField(null=True, verbose_name='availableBottles'),
        ),
        migrations.AddField(
            model_name='karekhbanks',
            name='bloodType',
            field=models.CharField(max_length=3, null=True, verbose_name='bloodType'),
        ),
        migrations.AddField(
            model_name='rassafabanks',
            name='availableBottles',
            field=models.IntegerField(null=True, verbose_name='availableBottles'),
        ),
        migrations.AddField(
            model_name='rassafabanks',
            name='bloodType',
            field=models.CharField(max_length=3, null=True, verbose_name='bloodType'),
        ),
        migrations.AlterField(
            model_name='karekhbanks',
            name='hospitalAddress',
            field=models.CharField(max_length=255, null=True, verbose_name='hospitalAddress'),
        ),
        migrations.AlterField(
            model_name='karekhbanks',
            name='hospitalName',
            field=models.CharField(max_length=250, null=True, verbose_name='hospitalName'),
        ),
        migrations.AlterField(
            model_name='karekhbanks',
            name='hospitalNumber',
            field=models.IntegerField(null=True, verbose_name='hospitalNumber'),
        ),
        migrations.AlterField(
            model_name='rassafabanks',
            name='hospitalAddress',
            field=models.CharField(max_length=255, null=True, verbose_name='hospitalAddress'),
        ),
        migrations.AlterField(
            model_name='rassafabanks',
            name='hospitalName',
            field=models.CharField(max_length=250, null=True, verbose_name='hospitalName'),
        ),
        migrations.AlterField(
            model_name='rassafabanks',
            name='hospitalNumber',
            field=models.IntegerField(null=True, verbose_name='hospitalNumber'),
        ),
    ]
