# Generated by Django 3.2.9 on 2022-02-19 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0004_auto_20220217_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('volunteerName', models.CharField(max_length=250, null=True, verbose_name='volunteerName')),
                ('volunteerAddress', models.CharField(max_length=255, null=True, verbose_name='volunteerAddress')),
                ('volunteerBloodType', models.CharField(max_length=3, null=True, verbose_name='volunteerBloodType')),
                ('volunteerPhoneNumber', models.IntegerField(null=True, verbose_name='volunteerPhoneNumber')),
            ],
        ),
    ]
