# Generated by Django 3.2.9 on 2022-02-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0005_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='volunteerAge',
            field=models.CharField(max_length=250, null=True, verbose_name='volunteerAge'),
        ),
    ]
