# Generated by Django 3.2.9 on 2022-02-22 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0007_alter_volunteers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='volunteerAge',
            field=models.IntegerField(max_length=250, null=True, verbose_name='volunteerAge'),
        ),
    ]
